### ISSUE TITLE
Communication question

### ISSUE THREAD

**Issue by maDnemo** [encryptogroup/MOTION#7]
I am trying to write a program that runs both Motion and another MPC framework that uses emp-tools' NetIO, is it possible for both to use the same communication channel?

**Comment by Oleksandr-Tkachenko** [comment]
I briefly looked into the docs for `NetIO` and it seems to be just a wrapper over a network socket. So the answer is no unless the other framework serializes its communication.  Otherwise, you would need to kind of manually synchronize the communication in both frameworks, which is quite non-trivial.
